//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace StormTestProject.StormModel
{
    using System;
    using System.Data;
    using System.Data.SqlClient;
	using System.Collections.Generic;

    public class EntityWithGuidCiService : ICiService<EntityWithGuid>
    {
        public List<EntityWithGuid> Materialize(string query, 
                            SqlParameter[] parms, 
                            SqlConnection conn, 
                            SqlTransaction trans)
        {
            Func<SqlDataReader, List<EntityWithGuid>> func = reader =>
            {
                var list = new List<EntityWithGuid>();
                while (reader.Read())
                {
                    var entity = new EntityWithGuid();
                    list.Add(PopulateFields(entity, reader));
                }
                return list;
            };
            return CiHelper.ExecuteSelect(query, parms, func, conn, trans);
        }

        private EntityWithGuid PopulateFields(EntityWithGuid entity, SqlDataReader reader)
        {
            entity.Id = reader.GetGuid(0);
            entity.AFloat = reader.IsDBNull(1) ? (double?)null : reader.GetDouble(1);
            entity.AReal = reader.GetFloat(2);
            entity.ADate = reader.IsDBNull(3) ? (DateTime?)null : reader.GetDateTime(3);
            entity.ATime = reader.IsDBNull(4) ? (TimeSpan?)null : reader.GetTimeSpan(4);
            entity.AOffset = reader.IsDBNull(5) ? (DateTimeOffset?)null : reader.GetDateTimeOffset(5);
            entity.ADatetime = reader.IsDBNull(6) ? (DateTime?)null : reader.GetDateTime(6);
            entity.ADatetime2 = reader.IsDBNull(7) ? (DateTime?)null : reader.GetDateTime(7);
            entity.ASmalldatetime = reader.IsDBNull(8) ? (DateTime?)null : reader.GetDateTime(8);
            return entity;
        }
    }
}
