//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace StormTestProject.StormModel
{
    using System;
    using System.Data;
    using System.Data.SqlClient;
	using System.Collections.Generic;

    public class EntityWithoutKeyCiService : ICiService<EntityWithoutKey>
    {
        public List<EntityWithoutKey> Materialize(string query, 
                            SqlParameter[] parms, 
                            SqlConnection conn, 
                            SqlTransaction trans)
        {
            Func<SqlDataReader, List<EntityWithoutKey>> func = reader =>
            {
                var list = new List<EntityWithoutKey>();
                while (reader.Read())
                {
                    var entity = new EntityWithoutKey();
                    list.Add(PopulateFields(entity, reader));
                }
                return list;
            };
            return CiHelper.ExecuteSelect(query, parms, func, conn, trans);
        }

        private EntityWithoutKey PopulateFields(EntityWithoutKey entity, SqlDataReader reader)
        {
            entity.Value = reader.GetInt32(0);
            entity.Content = reader.IsDBNull(1) ? null : reader.GetString(1);
            return entity;
        }
    }
}
