//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace StormTestProject.StormSchema
{
    using System;
    using System.Data;
    using System.Data.SqlClient;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;

    public class EntityWithIdCiService : ICiService<EntityWithId>
    {
        private List<EntityWithId> ReadEntities(SqlDataReader reader)
        {
            var list = new List<EntityWithId>();
            while (reader.Read())
            {
                var entity = new EntityWithId
                {
                    Id = reader.GetInt32(0),
                    ABigint = reader.IsDBNull(1) ? (long?)null : reader.GetInt64(1),
                    AInt = reader.GetInt32(2),
                    ANumeric = reader.IsDBNull(3) ? (decimal?)null : reader.GetDecimal(3),
                    ABit = reader.IsDBNull(4) ? (bool?)null : reader.GetBoolean(4),
                    ASmallint = reader.IsDBNull(5) ? (short?)null : reader.GetInt16(5),
                    ADecimal = reader.IsDBNull(6) ? (decimal?)null : reader.GetDecimal(6),
                    ASmallmoney = reader.IsDBNull(7) ? (decimal?)null : reader.GetDecimal(7),
                    ATinyint = reader.IsDBNull(8) ? (byte?)null : reader.GetByte(8),
                    AMoney = reader.IsDBNull(9) ? (decimal?)null : reader.GetDecimal(9),
                };
                list.Add(entity);
            }
            return list;
        }

        public List<EntityWithId> Get(string query, 
            SqlParameter[] parms, 
            SqlConnection conn, 
            SqlTransaction trans)
        {
            using (new ConnectionHandler(conn))
            {
                return CiHelper.ExecuteSelect(query, parms, ReadEntities, conn, trans);
            }
        }

        public static int MaxAmountForWhereIn = 300;

        public List<EntityWithId> GetByPrimaryKey(object ids, SqlConnection conn, SqlTransaction trans)
        {
            var idsArray = (int[])ids;
            using (new ConnectionHandler(conn))
            {
                return idsArray.Length > MaxAmountForWhereIn
                    ? GetByTempTable(idsArray, conn, trans)
                    : GetByWhereIn(idsArray, conn, trans);
            }
        }

        #region getByPrimaryKey internal methods
        private List<EntityWithId> GetByWhereIn(int[] idsArray, SqlConnection conn, SqlTransaction trans)
        {
            var whereIn = string.Join(", ", idsArray.Select((x,i) => "@arg" + i));
            var parms = idsArray.Select((x, i) => new SqlParameter("@arg" + i, x)).ToArray();
            var sql = @"select
                id, a_bigint, a_int, a_numeric, a_bit,
                a_smallint, a_decimal, a_smallmoney, a_tinyint, a_money
            from entity_with_id where id in (" + whereIn + ")";
            return CiHelper.ExecuteSelect(sql, parms, ReadEntities, conn, trans);
        }

        private List<EntityWithId> GetByTempTable(int[] idsArray, SqlConnection conn, SqlTransaction trans)
        {
                var table = CiHelper.CreateTempTableName();
                CreateIdTempTable(table, conn, trans);
                CiHelper.BulkInsert(new SingleKeyDataReader<int>(idsArray), table, conn, trans);
                var sql = @"select 
                e.id, e.a_bigint, e.a_int, e.a_numeric, e.a_bit,
                e.a_smallint, e.a_decimal, e.a_smallmoney, e.a_tinyint, e.a_money
                from entity_with_id e
                inner join " + table + @" t on 
                e.id = t.id";
                var result = CiHelper.ExecuteSelect(sql, new SqlParameter[0], ReadEntities, conn, trans);
                CiHelper.DropTable(table, conn, trans);
                return result;
        }

        private void CreateIdTempTable(string table, SqlConnection conn, SqlTransaction trans)
        {
            var sql = "CREATE TABLE " + table + " ( id int )";
            CiHelper.ExecuteNonQuery(sql, new SqlParameter[0], conn, trans);
        }
        #endregion

        public void Insert(List<EntityWithId> entities, SqlConnection conn, SqlTransaction trans)
        {        
           using(new ConnectionHandler(conn))
           {
               foreach(var group in entities.SplitInGroupsBy(83))
               {
                   RangeInsert(group, conn, trans);
               }
           }
        }

        #region range insert methods
        private void RangeInsert(List<EntityWithId> entities, SqlConnection conn, SqlTransaction trans)
        {
            int i = 0;
            var parms = entities.SelectMany(x => GetInsertParameters(x, i++)).ToArray();
            var sql = ConstructInsertRequest(entities.Count);
            CiHelper.ExecuteSelect(sql, parms, reader => ReadKey(reader, entities), conn, trans);
        }

        private List<EntityWithId> ReadKey(SqlDataReader reader, List<EntityWithId> entities)
        {
            int i = 0;
            while (reader.Read())
            {
                entities[i++].Id = reader.GetInt32(0);
            }

            return entities;
        }

        private string insertRequestCache;
        private int insertCacheLength;

        private string ConstructInsertRequest(int count)
        {
            if(insertCacheLength == count) return insertRequestCache;

            var sb = new StringBuilder();
            sb.AppendLine("INSERT INTO entity_with_id");
            sb.AppendLine("(");
            sb.AppendLine("a_bigint, a_int, a_numeric, a_bit, a_smallint,");
            sb.AppendLine("a_decimal, a_smallmoney, a_tinyint, a_money");
            sb.AppendLine(")OUTPUT inserted.id VALUES");

            AppendInsertKeys(sb, 0);
            for (int i = 1; i < count; i++)
            {
                sb.AppendLine("), ");
                AppendInsertKeys(sb, i);
            }
            
            sb.AppendLine(")");
            insertCacheLength = count;
            return insertRequestCache = sb.ToString();
        }

        private void AppendInsertKeys(StringBuilder sb, int i)
        {
                sb.Append("( @parm0i"); sb.Append(i);
                sb.Append(", @parm1i"); sb.Append(i);
                sb.Append(", @parm2i"); sb.Append(i);
                sb.Append(", @parm3i"); sb.Append(i);
                sb.Append(", @parm4i"); sb.Append(i);
                sb.Append(", @parm5i"); sb.Append(i);
                sb.Append(", @parm6i"); sb.Append(i);
                sb.Append(", @parm7i"); sb.Append(i);
                sb.Append(", @parm8i"); sb.Append(i);
        }

        private IEnumerable<SqlParameter> GetInsertParameters(EntityWithId entity, int i)
        {
            yield return new SqlParameter("parm0i" + i, SqlDbType.BigInt)
                { Value = entity.ABigint ?? (object)DBNull.Value };
            yield return new SqlParameter("parm1i" + i, SqlDbType.Int)
                { Value = entity.AInt };
            yield return new SqlParameter("parm2i" + i, SqlDbType.Decimal)
                { Value = entity.ANumeric ?? (object)DBNull.Value };
            yield return new SqlParameter("parm3i" + i, SqlDbType.Bit)
                { Value = entity.ABit ?? (object)DBNull.Value };
            yield return new SqlParameter("parm4i" + i, SqlDbType.SmallInt)
                { Value = entity.ASmallint ?? (object)DBNull.Value };
            yield return new SqlParameter("parm5i" + i, SqlDbType.Decimal)
                { Value = entity.ADecimal ?? (object)DBNull.Value };
            yield return new SqlParameter("parm6i" + i, SqlDbType.SmallMoney)
                { Value = entity.ASmallmoney ?? (object)DBNull.Value };
            yield return new SqlParameter("parm7i" + i, SqlDbType.TinyInt)
                { Value = entity.ATinyint ?? (object)DBNull.Value };
            yield return new SqlParameter("parm8i" + i, SqlDbType.Money)
                { Value = entity.AMoney ?? (object)DBNull.Value };
        }
        #endregion

        public void Insert(EntityWithId entity, SqlConnection conn, SqlTransaction trans)
        {        
            using(new ConnectionHandler(conn))
            {
                var sql = ConstructInsertRequest(1);    
                var parms = GetInsertParameters(entity, 0).ToArray();
                Func<IDataReader, List<EntityWithId>> readId = reader =>
                    {
                        if(reader.Read()) entity.Id = reader.GetInt32(0);
                        return null;
                    };
                CiHelper.ExecuteSelect(sql, parms, readId, conn, trans);
            }
        }

    }
}
