//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace StormTestProject
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;
    using St.Orm;
    using St.Orm.Interfaces;

    [Table("model.assignment")]
    public partial class Assignment : ICloneable<Assignment>
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column("assignment_id", Order = 1)]
        public int AssignmentId { get;set; }

        [Column("policy_id", Order = 2)]
        public int PolicyId { get;set; }

        [MaxLength(256)]
        [Column("comment", Order = 3)]
        public string Comment { get;set; }

        [Column("created", Order = 4)]
        public DateTime Created { get;set; }

        [Column("updated", Order = 5)]
        public DateTime Updated { get;set; }

        #region Navigation properties
        public virtual ICollection<Department> Departments
        {
            #region implementation
            get
            {
                if(populated[0])
                {
                    return field0;
                }

                populated[0] = true;
                return field0;
            }
            set
            {
                field0 = value;
                populated[0] = true;
            }
            #endregion
        }

        public virtual ICollection<Eligibility> Eligibilities
        {
            #region implementation
            get
            {
                if(populated[1])
                {
                    return field1;
                }

                populated[1] = true;
                return field1;
            }
            set
            {
                field1 = value;
                populated[1] = true;
            }
            #endregion
        }

        public virtual ICollection<Premium> Premiums
        {
            #region implementation
            get
            {
                if(populated[2])
                {
                    return field2;
                }

                Func<IQueryable<Premium>> query = () =>
                {
                    return loadService.Context.Set<Premium>()
                        .Join(sourceQuery, x => x.AssignmentId, x => x.AssignmentId, (x, y) => x);
                };
                populated[2] = true;
                return field2;
            }
            set
            {
                field2 = value;
                populated[2] = true;
            }
            #endregion
        }

        public virtual ICollection<Covered> Covereds
        {
            #region implementation
            get
            {
                if(populated[3])
                {
                    return field3;
                }

                Func<IQueryable<Covered>> query = () =>
                {
                    return loadService.Context.Set<Covered>()
                        .Join(sourceQuery, x => x.AssignmentId, x => x.AssignmentId, (x, y) => x);
                };
                populated[3] = true;
                return field3;
            }
            set
            {
                field3 = value;
                populated[3] = true;
            }
            #endregion
        }

        #endregion

        #region Private fields
        private readonly bool[] populated = new bool[4];
        private readonly ILoadService loadService;
        IQueryable<Assignment> sourceQuery;
        private readonly Assignment clonedFrom;
        private ICollection<Department> field0;
        private ICollection<Eligibility> field1;
        private ICollection<Premium> field2;
        private ICollection<Covered> field3;
        #endregion

        #region Constructors
        public Assignment(Assignment clonedFrom, IQueryable<Assignment> sourceQuery, ILoadService loadService)
        {
            this.clonedFrom = clonedFrom;
            this.loadService = loadService;
            this.sourceQuery = sourceQuery;
        }

        public Assignment(IQueryable<Assignment> sourceQuery, ILoadService loadService)
        {
            this.loadService = loadService;
            this.sourceQuery = sourceQuery;
        }

        public Assignment()
        {
            Departments = new HashSet<Department>();
            Eligibilities = new HashSet<Eligibility>();
            Premiums = new HashSet<Premium>();
            Covereds = new HashSet<Covered>();
        }
        #endregion

        #region ICloneable implementation
        Assignment ICloneable<Assignment>.Clone()
        {
            return new Assignment(this, sourceQuery, loadService)
            {
                AssignmentId = AssignmentId,
                PolicyId = PolicyId,
                Comment = Comment,
                Created = Created,
                Updated = Updated,
            };
        }

        Assignment ICloneable<Assignment>.ClonedFrom()
        {
            return clonedFrom;
        }

        bool[] ICloneable<Assignment>.GetPopulated()
        {
            return populated;
        }
        #endregion
    }
}
