//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace StormTestProject
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Linq;
    using St.Orm;
    using St.Orm.Interfaces;

    internal class AssignmentEligibilityDalRepository : IDalRepository<AssignmentEligibility, AssignmentEligibility>
    {
        private IDalRepositoryExtension<AssignmentEligibility> extension;

        public AssignmentEligibilityDalRepository()
        {
            extension = new EmptyRepositoryExtension<AssignmentEligibility>();
        }

        public void SetExtension(IDalRepositoryExtension<AssignmentEligibility> extension)
        {
            this.extension = extension;
        }

        public int RelationsCount()
        {
            return extension.RelationsCount() ?? 1;
        }

        public AssignmentEligibility Clone(AssignmentEligibility source)
        {
            var clone = (source as ICloneable<AssignmentEligibility>).Clone();
            extension.ExtendClone(clone, source);
            return clone;
        }

        public AssignmentEligibility Create(IDataReader reader, IQueryable<AssignmentEligibility> query, ILoadService loadService)
        {
            var entity = new AssignmentEligibility(query, loadService)
            {
                AssignmentId = reader.GetInt32(0),
                EligibilityId = reader.GetInt32(1),
                Created = reader.GetDateTime(2),
                Updated = reader.GetDateTime(3),
            };
            extension.ExtendCreate(entity, reader);
            return entity;
        }

        public List<AssignmentEligibility> Materialize(IQueryable<AssignmentEligibility> query, ILoadService loadService)
        {
            var context = loadService.Context;
            return AdoCommands.Materialize(query,
                reader => Create(reader, query, loadService),
                context.Connection,
                context.Transaction);
        }

        public IQueryable<AssignmentEligibility> GetByIdQuery(object id, IStormContext context)
        {
            throw new Exception("Get by id is only available for entities with single primary key field.");
        }
    }
}
