//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace StormTestProject
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Linq;
    using St.Orm;
    using St.Orm.Interfaces;

    internal class AssignmentDalRepository : IDalRepository<Assignment, Assignment>
    {
        private IDalRepositoryExtension<Assignment> extension;

        public AssignmentDalRepository()
        {
            extension = new EmptyRepositoryExtension<Assignment>();
        }

        public void SetExtension(IDalRepositoryExtension<Assignment> extension)
        {
            this.extension = extension;
        }

        public int RelationsCount()
        {
            return extension.RelationsCount() ?? 4;
        }

        public Assignment Clone(Assignment source)
        {
            var clone = (source as ICloneable<Assignment>).Clone();
            extension.ExtendClone(clone, source);
            return clone;
        }

        public Assignment Create(IDataReader reader, IQueryable<Assignment> query, ILoadService loadService)
        {
            var entity = new Assignment(query, loadService)
            {
                AssignmentId = reader.GetInt32(0),
                PolicyId = reader.GetInt32(1),
                Comment = reader[2] as string,
                Created = reader.GetDateTime(3),
                Updated = reader.GetDateTime(4),
            };
            extension.ExtendCreate(entity, reader);
            return entity;
        }

        public List<Assignment> Materialize(IQueryable<Assignment> query, ILoadService loadService)
        {
            var context = loadService.Context;
            return AdoCommands.Materialize(query,
                reader => Create(reader, query, loadService),
                context.Connection,
                context.Transaction);
        }

        public IQueryable<Assignment> GetByIdQuery(object id, IStormContext context)
        {
            var key = (int)id;
            return context.Set<Assignment>().Where(x => x.AssignmentId == key);
        }
    }
}
