//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace StormTestProject
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("calculation_details")]
    public partial class CalculationDetails
    {
        private CalculationDetails clonedFrom;

        public CalculationDetails(CalculationDetails clonedFrom)
        {
            this.clonedFrom = clonedFrom;
        }

        public CalculationDetails() { }

        [Key]
        [Column("calculation_details_id")]
        public Guid CalculationDetailsId { get;set; }

        [Column("calculation_id")]
        public Guid CalculationId { get;set; }

        [Column("year")]
        public int Year { get;set; }

        [Column("month")]
        public int Month { get;set; }

        [Column("value")]
        public decimal Value { get;set; }
    }
}
