//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace StormTestProject
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("StormTest.stats.calculation_details")]
    public partial class CalculationDetails
    {
        [Key]
        [Column("calculation_details_id", Order = 0)]
        public Guid CalculationDetailsId { get;set; }

        [Column("calculation_id", Order = 1)]
        public Guid CalculationId { get;set; }

        [Column("year", Order = 2)]
        public int Year { get;set; }

        [Column("month", Order = 3)]
        public int Month { get;set; }

        [Column("value", Order = 4)]
        public decimal Value { get;set; }

        #region Private fields

        private CalculationDetails clonedFrom;

        #endregion

        #region Constructors

        public CalculationDetails(CalculationDetails clonedFrom)
        {
            this.clonedFrom = clonedFrom;
        }

        public CalculationDetails() { }

        #endregion

        #region Lazy properties

        #endregion
    }
}
