//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace StormTestProject
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("StormTest.dbo.comment")]
    public partial class Comment
    {
        [Key]
        [Column("comment_id", Order = 0)]
        public int CommentId { get;set; }

        [Column("comment_type", Order = 1)]
        public int CommentType { get;set; }

        [Column("policy_id", Order = 2)]
        public int? PolicyId { get;set; }

        [Column("premium_id", Order = 3)]
        public int? PremiumId { get;set; }

        [Required]
        [Column("comment_text", Order = 4)]
        public string CommentText { get;set; }

        [Column("author_user_id", Order = 5)]
        public int AuthorUserId { get;set; }

        [Column("created", Order = 6)]
        public DateTime Created { get;set; }

        [Column("updated", Order = 7)]
        public DateTime Updated { get;set; }

        #region Private fields

        private Comment clonedFrom;

        #endregion

        #region Constructors

        public Comment(Comment clonedFrom)
        {
            this.clonedFrom = clonedFrom;
        }

        public Comment() { }

        #endregion

        #region Lazy properties

        #endregion
    }
}
