//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace StormTestProject
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("comment")]
    public partial class Comment
    {
        private Comment clonedFrom;

        public Comment(Comment clonedFrom)
        {
            this.clonedFrom = clonedFrom;
        }

        public Comment() { }

        [Key]
        [Column("comment_id")]
        public int CommentId { get;set; }

        [Column("comment_type")]
        public int CommentType { get;set; }

        [Column("policy_id")]
        public int? PolicyId { get;set; }

        [Column("premium_id")]
        public int? PremiumId { get;set; }

        [Required]
        [Column("comment_text")]
        public string CommentText { get;set; }

        [Column("author_user_id")]
        public int AuthorUserId { get;set; }

        [Column("created")]
        public DateTime Created { get;set; }

        [Column("updated")]
        public DateTime Updated { get;set; }
    }
}
