//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace StormTestProject
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("StormTest.dbo.country")]
    public partial class Country
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column("country_id", Order = 0)]
        public int CountryId { get;set; }

        [Required]
        [MaxLength(256)]
        [Column("name", Order = 1)]
        public string Name { get;set; }

        [Required]
        [MaxLength(10)]
        [Column("country_code", Order = 2)]
        public string CountryCode { get;set; }

        [Column("created", Order = 3)]
        public DateTime Created { get;set; }

        [Column("updated", Order = 4)]
        public DateTime Updated { get;set; }

        public virtual List<Policy> Policies { get { return property0; } set { property0 = value; } }

        #region Private fields

        private Country clonedFrom;
        private Policy field0;

        #endregion

        #region Constructors

        public Country(Country clonedFrom)
        {
            this.clonedFrom = clonedFrom;
        }

        public Country() { }

        #endregion

        #region Lazy properties

        private List<Policy> property0 { get;set; }

        #endregion
    }
}
