//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace StormTestProject
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("country")]
    public partial class Country
    {
        private Country clonedFrom;

        public Country(Country clonedFrom)
        {
            this.clonedFrom = clonedFrom;
        }

        public Country() { }

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column("country_id")]
        public int CountryId { get;set; }

        [Required]
        [MaxLength(256)]
        [Column("name")]
        public string Name { get;set; }

        [Required]
        [MaxLength(10)]
        [Column("country_code")]
        public string CountryCode { get;set; }

        [Column("created")]
        public DateTime Created { get;set; }

        [Column("updated")]
        public DateTime Updated { get;set; }
    }
}
