//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace StormTestProject
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using St.Orm;
    using St.Orm.Interfaces;

    public partial class CoverageDepartment
    {
        public int CoverageId { get;set; }

        public int DepartmentId { get;set; }

        public virtual Department Department { get { return property0; } set { property0 = value; } }

        #region Private fields

        private readonly ILoadService loadService;
        private readonly CoverageDepartment clonedFrom;
        private Department field0;

        #endregion

        #region Constructors

        public CoverageDepartment(CoverageDepartment clonedFrom)
        {
            this.clonedFrom = clonedFrom;
            this.loadService = clonedFrom.GetLoadService();
        }

        public CoverageDepartment(ILoadService loadService)
        {
            this.loadService = loadService;
        }

        public CoverageDepartment()
        {
        }

        public ILoadService GetLoadService()
        {
            return loadService;
        }

        #endregion

        #region Lazy properties

        private Department property0 { get;set; }

        #endregion
    }
}
