//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace StormTestProject
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Linq;
    using St.Orm;
    using St.Orm.Interfaces;

    internal class CoveredDalRepository : IDalRepository<Covered, Covered>
    {
        private IDalRepositoryExtension<Covered> extension;

        public CoveredDalRepository()
        {
            extension = new EmptyRepositoryExtension<Covered>();
        }

        public void SetExtension(IDalRepositoryExtension<Covered> extension)
        {
            this.extension = extension;
        }

        public int NavPropsCount()
        {
            return extension.NavPropsCount() ?? 0;
        }

        public Covered Create(IDataReader reader, IQueryable<Covered> query, ILoadService loadService)
        {
            var entity = new Covered(query, loadService)
            {
                CoveredId = reader.GetInt32(0),
                CoveredType = reader.GetInt32(1),
                AssignmentId = reader.GetInt32(2),
                Headcount = reader.GetInt32(3),
                Created = reader.GetDateTime(4),
                Updated = reader.GetDateTime(5),
            };
            extension.ExtendCreate(entity, reader);
            return entity;
        }

        public Covered Clone(Covered source)
        {
            var clone = (source as ICloneable<Covered>).Clone();
            extension.ExtendClone(clone, source);
            return clone;
        }

        public List<Covered> Materialize(IQueryable<Covered> query, ILoadService loadService)
        {
            var context = loadService.Context;
            return AdoCommands.Materialize(query,
                reader => Create(reader, query, loadService),
                context.Connection,
                context.Transaction);
        }

        public IQueryable<Covered> GetByIdQuery(object id, IStormContext context)
        {
            var key = (int)id;
            return context.Set<Covered>().Where(x => x.CoveredId == key);
        }

        public void Save(Covered entity, ISavesCollector saves)
        {
            if(!extension.PreSave(entity))
            {
                return;
            }

            SetMtoFields(entity);
            saves.Save<Covered, Covered>(entity);
        }

        public void Update(Covered entity, Covered existing, ISavesCollector saves)
        {
            if(!extension.PreUpdate(entity, existing))
            {
                Delete(entity, saves);
                return;
            }

            SetMtoFields(entity);
            if (EntityChanged(entity, existing))
            {
                saves.Update<Covered, Covered>(entity, existing);
            }
            else
            {
                saves.NoUpdate<Covered, Covered>(entity, existing);
            }
        }

        public void Delete(Covered entity, ISavesCollector saves)
        {
            if(!extension.PreDelete(entity))
            {
                return;
            }

            DeleteRelations(entity, saves);
            saves.Delete<Covered, Covered>(entity);
        }

        public void SaveRelations(Covered entity, ISavesCollector saves)
        {
        }

        public void UpdateRelations(Covered entity, Covered existing, ISavesCollector saves)
        {
        }

        private void DeleteRelations(Covered entity, ISavesCollector saves)
        {
        }

        private void SetMtoFields(Covered entity)
        {
        }

        public bool EntityChanged(Covered entity, Covered existing)
        {
            return extension.ExtendEntityChanged(entity, existing)
                || entity.CoveredType != existing.CoveredType
                || entity.AssignmentId != existing.AssignmentId
                || entity.Headcount != existing.Headcount
                || entity.Created != existing.Created
                || entity.Updated != existing.Updated;
        }
    }
}
