//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace StormTestProject
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("coverage_eligibility_group")]
    public partial class CoverageEligibilityGroup
    {
        private CoverageEligibilityGroup clonedFrom;

        public CoverageEligibilityGroup(CoverageEligibilityGroup clonedFrom)
        {
            this.clonedFrom = clonedFrom;
        }

        public CoverageEligibilityGroup() { }

        [Key]
        [Column("coverage_id")]
        public int CoverageId { get;set; }

        [Key]
        [Column("eligibility_group_id")]
        public int EligibilityGroupId { get;set; }

        [Column("created")]
        public DateTime Created { get;set; }

        [Column("updated")]
        public DateTime Updated { get;set; }
    }
}
