//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace StormTestProject
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Linq;
    using St.Orm;
    using St.Orm.Interfaces;

    internal class CoverageEligibilityGroupDalRepository : IDalRepository<CoverageEligibilityGroup, CoverageEligibilityGroup>
    {
        private IDalRepositoryExtension<CoverageEligibilityGroup> extension;

        public CoverageEligibilityGroupDalRepository()
        {
            extension = new EmptyRepositoryExtension<CoverageEligibilityGroup>();
        }

        public void SetExtension(IDalRepositoryExtension<CoverageEligibilityGroup> extension)
        {
            this.extension = extension;
        }

        public int RelationsCount()
        {
            return extension.RelationsCount() ?? 1;
        }

        public CoverageEligibilityGroup Clone(CoverageEligibilityGroup source)
        {
            var clone = new CoverageEligibilityGroup(source)
            {
                CoverageId = source.CoverageId,
                EligibilityGroupId = source.EligibilityGroupId,
                Created = source.Created,
                Updated = source.Updated,
            };
            extension.ExtendClone(clone, source);
            return clone;
        }

        public CoverageEligibilityGroup Create(IDataReader reader, ILoadService loadService)
        {
            var entity = new CoverageEligibilityGroup(loadService)
            {
                CoverageId = reader.GetInt32(0),
                EligibilityGroupId = reader.GetInt32(1),
                Created = reader.GetDateTime(2),
                Updated = reader.GetDateTime(3),
            };
            extension.ExtendCreate(entity, reader);
            return entity;
        }

        public List<CoverageEligibilityGroup> Materialize(IQueryable<CoverageEligibilityGroup> query, ILoadService loadService)
        {
            var context = loadService.Context;
            return AdoCommands.Materialize(query as IQueryable<CoverageEligibilityGroup>,
                reader => Create(reader, loadService),
                context.Connection,
                context.Transaction);
        }
    }
}
