//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace StormTestProject
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("currency")]
    public partial class Currency
    {
        private Currency clonedFrom;

        public Currency(Currency clonedFrom)
        {
            this.clonedFrom = clonedFrom;
        }

        public Currency() { }

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column("currency_id")]
        public int CurrencyId { get;set; }

        [Required]
        [MaxLength(256)]
        [Column("name")]
        public string Name { get;set; }

        [Required]
        [MaxLength(10)]
        [Column("currency_code")]
        public string CurrencyCode { get;set; }

        [Column("created")]
        public DateTime Created { get;set; }

        [Column("updated")]
        public DateTime Updated { get;set; }
    }
}
