//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace StormTestProject
{
    using System;
    using System.Collections.Generic;
    using St.Orm.Interfaces;
    
    internal class DalRepositoryStorage : IDalRepositoryStorage
    {
        private readonly Dictionary<Type, object> repositories 
            = new Dictionary<Type, object>
                {
                    { typeof(Department), new DepartmentDalRepository() },
                    { typeof(EligibilityGroup), new EligibilityGroupDalRepository() },
                    { typeof(Currency), new CurrencyDalRepository() },
                    { typeof(Country), new CountryDalRepository() },
                    { typeof(CoverageEligibilityGroup), new CoverageEligibilityGroupDalRepository() },
                    { typeof(Calculation), new CalculationDalRepository() },
                    { typeof(CalculationDetails), new CalculationDetailsDalRepository() },
                    { typeof(Premium), new PremiumDalRepository() },
                    { typeof(Covered), new CoveredDalRepository() },
                    { typeof(Comment), new CommentDalRepository() },
                    { typeof(Policy), new PolicyDalRepository() },
                    { typeof(Tax), new TaxDalRepository() },
                    { typeof(Coverage), new CoverageDalRepository() },
                    { typeof(CoverageDepartment), new CoverageDepartmentDalRepository() },
                };
    
        public IDalRepository<T> GetDalRepository<T>()
        {
            return repositories[typeof(T)] as IDalRepository<T>;
        }
    }
}
