//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace StormTestProject
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("StormTest.dbo.department")]
    public partial class Department
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column("department_id", Order = 0)]
        public int DepartmentId { get;set; }

        [Required]
        [MaxLength(256)]
        [Column("name", Order = 1)]
        public string Name { get;set; }

        [Column("created", Order = 2)]
        public DateTime Created { get;set; }

        [Column("updated", Order = 3)]
        public DateTime Updated { get;set; }

        public virtual List<Coverage> Coverages { get { return property0; } set { property0 = value; } }

        public virtual List<Coverage> Coverages { get { return property1; } set { property1 = value; } }

        #region Private fields

        private Department clonedFrom;
        private Coverage field0;
        private Coverage field1;

        #endregion

        #region Constructors

        public Department(Department clonedFrom)
        {
            this.clonedFrom = clonedFrom;
        }

        public Department() { }

        #endregion

        #region Lazy properties

        private List<Coverage> property0 { get;set; }

        private List<Coverage> property1 { get;set; }

        #endregion
    }
}
