//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace StormTestProject
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("emp")]
    public partial class Emp
    {
        private Emp clonedFrom;

        public Emp(Emp clonedFrom)
        {
            this.clonedFrom = clonedFrom;
        }

        public Emp() { }

        [Key]
        [Required]
        [MaxLength(9)]
        [Column("ssn")]
        public string Ssn { get;set; }

        [Key]
        [Required]
        [MaxLength(15)]
        [Column("client")]
        public string Client { get;set; }
    }
}
