//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace StormTestProject
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("StormTest.dbo.emp")]
    public partial class Emp
    {
        [Key]
        [Required]
        [MaxLength(9)]
        [Column("ssn", Order = 1)]
        public string Ssn { get;set; }

        [Key]
        [Required]
        [MaxLength(15)]
        [Column("client", Order = 2)]
        public string Client { get;set; }

        public virtual List<EmpToDependent> EmpToDependents { get { return property0; } set { property0 = value; } }

        public virtual List<EmpToDependent> EmpToDependents2 { get { return property1; } set { property1 = value; } }

        #region Private fields

        private Emp clonedFrom;
        private EmpToDependent field0;
        private EmpToDependent field1;

        #endregion

        #region Constructors

        public Emp(Emp clonedFrom)
        {
            this.clonedFrom = clonedFrom;
        }

        public Emp() { }

        #endregion

        #region Lazy properties

        private List<EmpToDependent> property0 { get;set; }

        private List<EmpToDependent> property1 { get;set; }

        #endregion
    }
}
