//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace StormTestProject
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("emp_to_dependent")]
    public partial class EmpToDependent
    {
        private EmpToDependent clonedFrom;

        public EmpToDependent(EmpToDependent clonedFrom)
        {
            this.clonedFrom = clonedFrom;
        }

        public EmpToDependent() { }

        [Key]
        [Required]
        [MaxLength(9)]
        [Column("ssn")]
        public string Ssn { get;set; }

        [Key]
        [Required]
        [MaxLength(15)]
        [Column("client")]
        public string Client { get;set; }

        [Key]
        [Required]
        [MaxLength(9)]
        [Column("dep_ssn")]
        public string DepSsn { get;set; }

        [Key]
        [Required]
        [MaxLength(15)]
        [Column("dep_client")]
        public string DepClient { get;set; }
    }
}
