//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace StormTestProject
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;
    using St.Orm;
    using St.Orm.Interfaces;

    [Table("model.policy")]
    public partial class Policy : ICloneable<Policy>
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column("policy_id", Order = 1)]
        public int PolicyId { get;set; }

        [Column("country_id", Order = 2)]
        public int? CountryId { get;set; }

        [Column("currency_id", Order = 3)]
        public int CurrencyId { get;set; }

        [Required]
        [MaxLength(256)]
        [Column("name", Order = 4)]
        public string Name { get;set; }

        [Column("created", Order = 5)]
        public DateTime Created { get;set; }

        [Column("updated", Order = 6)]
        public DateTime Updated { get;set; }

        #region Navigation properties
        public virtual Country Country
        {
            #region implementation
            get
            {
                if(populated[0])
                {
                    return field0;
                }

                populated[0] = true;
                return field0;
            }
            set
            {
                field0 = value;
                populated[0] = true;
            }
            #endregion
        }

        public virtual ICollection<Tax> Taxes
        {
            #region implementation
            get
            {
                if(populated[1])
                {
                    return field1;
                }

                Func<IQueryable<Tax>> query = () =>
                {
                    return loadService.Context.Set<Tax>()
                        .Join(sourceQuery, x => x.PolicyId, x => x.PolicyId, (x, y) => x);
                };

                var items = loadService.GetProperty<Tax, Tax, int>(0, query, x => x.PolicyId, PolicyId);

                populated[1] = true;
                return field1;
            }
            set
            {
                field1 = value;
                populated[1] = true;
            }
            #endregion
        }

        public virtual ICollection<Assignment> Assignments
        {
            #region implementation
            get
            {
                if(populated[2])
                {
                    return field2;
                }

                Func<IQueryable<Assignment>> query = () =>
                {
                    return loadService.Context.Set<Assignment>()
                        .Join(sourceQuery, x => x.PolicyId, x => x.PolicyId, (x, y) => x);
                };
                populated[2] = true;
                return field2;
            }
            set
            {
                field2 = value;
                populated[2] = true;
            }
            #endregion
        }

        public virtual ICollection<Comment> Comments
        {
            #region implementation
            get
            {
                if(populated[3])
                {
                    return field3;
                }

                Func<IQueryable<Comment>> query = () =>
                {
                    return loadService.Context.Set<Comment>()
                        .Join(sourceQuery, x => x.PolicyId.Value, x => x.PolicyId, (x, y) => x);
                };
                populated[3] = true;
                return field3;
            }
            set
            {
                field3 = value;
                populated[3] = true;
            }
            #endregion
        }

        #endregion

        #region Private fields
        private readonly bool[] populated = new bool[4];
        private readonly ILoadService loadService;
        IQueryable<Policy> sourceQuery;
        private readonly Policy clonedFrom;
        private Country field0;
        private ICollection<Tax> field1;
        private ICollection<Assignment> field2;
        private ICollection<Comment> field3;
        #endregion

        #region Constructors
        public Policy(Policy clonedFrom, IQueryable<Policy> sourceQuery, ILoadService loadService)
        {
            this.clonedFrom = clonedFrom;
            this.loadService = loadService;
            this.sourceQuery = sourceQuery;
        }

        public Policy(IQueryable<Policy> sourceQuery, ILoadService loadService)
        {
            this.loadService = loadService;
            this.sourceQuery = sourceQuery;
        }

        public Policy()
        {
            Taxes = new HashSet<Tax>();
            Assignments = new HashSet<Assignment>();
            Comments = new HashSet<Comment>();
        }
        #endregion

        #region ICloneable implementation
        Policy ICloneable<Policy>.Clone()
        {
            return new Policy(this, sourceQuery, loadService)
            {
                PolicyId = PolicyId,
                CountryId = CountryId,
                CurrencyId = CurrencyId,
                Name = Name,
                Created = Created,
                Updated = Updated,
            };
        }

        Policy ICloneable<Policy>.ClonedFrom()
        {
            return clonedFrom;
        }

        bool[] ICloneable<Policy>.GetPopulated()
        {
            return populated;
        }
        #endregion
    }
}
