//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace StormTestProject
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Linq;
    using St.Orm;
    using St.Orm.Interfaces;

    internal class PolicyDalRepository : IDalRepository<Policy, Policy>
    {
        private IDalRepositoryExtension<Policy> extension;

        public PolicyDalRepository()
        {
            extension = new EmptyRepositoryExtension<Policy>();
        }

        public void SetExtension(IDalRepositoryExtension<Policy> extension)
        {
            this.extension = extension;
        }

        public int NavPropsCount()
        {
            return extension.NavPropsCount() ?? 4;
        }

        public Policy Create(IDataReader reader, IQueryable<Policy> query, ILoadService loadService)
        {
            var entity = new Policy(query, loadService)
            {
                PolicyId = reader.GetInt32(0),
                CountryId = reader[1] as int?,
                CurrencyId = reader.GetInt32(2),
                Name = reader[3] as string,
                Created = reader.GetDateTime(4),
                Updated = reader.GetDateTime(5),
            };
            extension.ExtendCreate(entity, reader);
            return entity;
        }

        public Policy Clone(Policy source)
        {
            var clone = (source as ICloneable<Policy>).Clone();
            extension.ExtendClone(clone, source);
            return clone;
        }

        public List<Policy> Materialize(IQueryable<Policy> query, ILoadService loadService)
        {
            var context = loadService.Context;
            return AdoCommands.Materialize(query,
                reader => Create(reader, query, loadService),
                context.Connection,
                context.Transaction);
        }

        public IQueryable<Policy> GetByIdQuery(object id, IStormContext context)
        {
            var key = (int)id;
            return context.Set<Policy>().Where(x => x.PolicyId == key);
        }

        public void Save(Policy entity, ISavesCollector saves)
        {
            if(!extension.PreSave(entity))
            {
                return;
            }

            SetMtoFields(entity);
            saves.Save<Policy, Policy>(entity);
        }

        public void Update(Policy entity, Policy existing, ISavesCollector saves)
        {
            if(!extension.PreUpdate(entity, existing))
            {
                Delete(entity, saves);
                return;
            }

            SetMtoFields(entity);
            if (EntityChanged(entity, existing))
            {
                saves.Update<Policy, Policy>(entity, existing);
            }
            else
            {
                saves.NoUpdate<Policy, Policy>(entity, existing);
            }
        }

        public void Delete(Policy entity, ISavesCollector saves)
        {
            if(!extension.PreDelete(entity))
            {
                return;
            }

            DeleteRelations(entity, saves);
            saves.Delete<Policy, Policy>(entity);
        }

        public void SaveRelations(Policy entity, ISavesCollector saves)
        {
        }

        public void UpdateRelations(Policy entity, Policy existing, ISavesCollector saves)
        {
        }

        private void DeleteRelations(Policy entity, ISavesCollector saves)
        {
        }

        private void SetMtoFields(Policy entity)
        {
            if(entity.Country != null)
            {
                entity.CountryId = entity.Country.CountryId;
            }
        }

        public bool EntityChanged(Policy entity, Policy existing)
        {
            return extension.ExtendEntityChanged(entity, existing)
                || entity.CountryId != existing.CountryId
                || entity.CurrencyId != existing.CurrencyId
                || entity.Name != existing.Name
                || entity.Created != existing.Created
                || entity.Updated != existing.Updated;
        }
    }
}
