//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace StormTestProject
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;
    using St.Orm;
    using St.Orm.Interfaces;

    [Table("model.premium")]
    public partial class Premium
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column("premium_id", Order = 1)]
        public int PremiumId { get;set; }

        [Column("premium_type", Order = 2)]
        public int PremiumType { get;set; }

        [Column("coverage_id", Order = 3)]
        public int CoverageId { get;set; }

        [Column("amount", Order = 4)]
        public decimal Amount { get;set; }

        [Column("created", Order = 5)]
        public DateTime Created { get;set; }

        [Column("updated", Order = 6)]
        public DateTime Updated { get;set; }

        public virtual ICollection<Comment> Comments { get { return property0; } set { property0 = value; } }

        #region Private fields

        private readonly ILoadService loadService;
        private readonly Premium clonedFrom;
        private Comment field0;

        #endregion

        #region Constructors

        public Premium(Premium clonedFrom)
        {
            this.clonedFrom = clonedFrom;
            this.loadService = clonedFrom.GetLoadService();
        }

        public Premium(ILoadService loadService)
        {
            this.loadService = loadService;
        }

        public Premium()
        {
            Comments = new HashSet<Comment>();
        }

        public ILoadService GetLoadService()
        {
            return loadService;
        }

        #endregion

        #region Lazy properties

        private ICollection<Comment> property0 { get;set; }

        #endregion
    }
}
