//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace StormTestProject
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("premium")]
    public partial class Premium
    {
        private Premium clonedFrom;

        public Premium(Premium clonedFrom)
        {
            this.clonedFrom = clonedFrom;
        }

        public Premium() { }

        [Key]
        [Column("premium_id")]
        public int PremiumId { get;set; }

        [Column("premium_type")]
        public int PremiumType { get;set; }

        [Column("coverage_id")]
        public int CoverageId { get;set; }

        [Column("amount")]
        public decimal Amount { get;set; }

        [Column("created")]
        public DateTime Created { get;set; }

        [Column("updated")]
        public DateTime Updated { get;set; }
    }
}
