//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace StormTestProject
{
    using System.Collections.Generic;
    using System.Linq;
    using St.Orm;    
    using St.Orm.Interfaces;    
    using St.Orm.Parameters;

    public class StormCommands
    {
        private readonly IStormContext context;

        public StormCommands(IStormContext context)
        {
            this.context = context;
        }

        public ICollection<T> Get<T>(IQueryable<T> query, params LoadParameter[] parameters)
        {
            return Storm.Get(query, context, parameters);
        }

        public T GetById<T>(object id, params LoadParameter[] parameters) where T : IHaveId
        {
            return Storm.GetById<T>(id, context, parameters);
        }
    }
}
