//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace StormTestProject
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("StormTest.dbo.tax")]
    public partial class Tax
    {
        [Key]
        [Column("tax_id", Order = 0)]
        public int TaxId { get;set; }

        [Column("policy_id", Order = 1)]
        public int PolicyId { get;set; }

        [Column("amount", Order = 2)]
        public decimal Amount { get;set; }

        [Column("created", Order = 3)]
        public DateTime Created { get;set; }

        [Column("updated", Order = 4)]
        public DateTime Updated { get;set; }

        #region Private fields

        private Tax clonedFrom;

        #endregion

        #region Constructors

        public Tax(Tax clonedFrom)
        {
            this.clonedFrom = clonedFrom;
        }

        public Tax() { }

        #endregion

        #region Lazy properties

        #endregion
    }
}
