//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace StormTestProject
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Linq;
    using St.Orm;
    using St.Orm.Interfaces;

    internal class TaxDalRepository : IDalRepository<Tax, Tax>
    {
        private IDalRepositoryExtension<Tax> extension;

        public TaxDalRepository()
        {
            extension = new EmptyRepositoryExtension<Tax>();
        }

        public void SetExtension(IDalRepositoryExtension<Tax> extension)
        {
            this.extension = extension;
        }

        public int RelationsCount()
        {
            return extension.RelationsCount() ?? 0;
        }

        public Tax Clone(Tax source)
        {
            var clone = (source as ICloneable<Tax>).Clone();
            extension.ExtendClone(clone, source);
            return clone;
        }

        public Tax Create(IDataReader reader, IQueryable<Tax> query, ILoadService loadService)
        {
            var entity = new Tax(query, loadService)
            {
                TaxId = reader.GetInt32(0),
                PolicyId = reader.GetInt32(1),
                Amount = reader.GetDecimal(2),
                Created = reader.GetDateTime(3),
                Updated = reader.GetDateTime(4),
            };
            extension.ExtendCreate(entity, reader);
            return entity;
        }

        public List<Tax> Materialize(IQueryable<Tax> query, ILoadService loadService)
        {
            var context = loadService.Context;
            return AdoCommands.Materialize(query,
                reader => Create(reader, query, loadService),
                context.Connection,
                context.Transaction);
        }
    }
}
