//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace StormGenerator.Generation.Generators.MsSqlCiServices.CiServiceMethods
{
    using StormGenerator.Settings;
    using StormGenerator.Models.GenModels;
    using GeneratorHelpers;
    using System.Collections.Generic;
    using System;
    using System.Text;
    using System.Linq;

    [System.CodeDom.Compiler.GeneratedCode("SharpRazor", "1.0.0.0")]
    internal class CreateTableContent
    {
        #region constructor
        List<Field> fields;

        public CreateTableContent(List<Field> fields)
        {
            this.fields = fields;
        }
        #endregion

        #region basic members
        private readonly StringBuilder sb = new StringBuilder();
        private string executed;

        private void WriteLiteral(string text)
        {
            if (!string.IsNullOrEmpty(text))
            {
                sb.Append(text);
            }
        }

        private void Write(object value)
        {
            if (value != null)
            {
                sb.Append(value);
            }
        }

        public override string ToString()
        {
            return executed;
        }
        #endregion

        public string Execute()
        {
            WriteLiteral(@"            var sql = ""CREATE TABLE "" + table + ");
            WriteLiteral(@"@");
            WriteLiteral(@"""(");
            WriteLiteral(Environment.NewLine);
            foreach (var field in fields)
            {
                WriteLiteral(@"                ");
                Write(field.Column.Definition);
                if (field != fields.Last())
                {
                    WriteLiteral(@",");
                }
                WriteLiteral(Environment.NewLine);
            }
            WriteLiteral(@"                )"";");
            WriteLiteral(Environment.NewLine);
            WriteLiteral(@"            CiHelper.ExecuteNonQuery(sql, CiHelper.NoParameters, conn, trans);");
            WriteLiteral(Environment.NewLine);

            return executed = sb.ToString();
        }
    }
}
