//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace StormGenerator.Generation.Generators.MsSqlCiServices.CiServiceMethods
{
    using StormGenerator.Settings;
    using StormGenerator.Models.GenModels;
    using GeneratorHelpers;
    using System;
    using System.Text;
    using System.Linq;

    [System.CodeDom.Compiler.GeneratedCode("SharpRazor", "1.0.0.0")]
    internal class GetBySinglePrimaryKey
    {
        #region constructor
        Model model;

        public GetBySinglePrimaryKey(Model model)
        {
            this.model = model;
        }
        #endregion

        #region basic members
        private readonly StringBuilder sb = new StringBuilder();
        private string executed;

        private void WriteLiteral(string text)
        {
            if (!string.IsNullOrEmpty(text))
            {
                sb.Append(text);
            }
        }

        private void Write(object value)
        {
            if (value != null)
            {
                sb.Append(value);
            }
        }

        public override string ToString()
        {
            return executed;
        }
        #endregion

        public string Execute()
        {
            WriteLiteral(@"        public List<");
            Write(model.Name);
            WriteLiteral(@"> GetByPrimaryKey(object ids, SqlConnection conn, SqlTransaction trans)");
            WriteLiteral(Environment.NewLine);
            WriteLiteral(@"        {");
            WriteLiteral(Environment.NewLine);
            WriteLiteral(@"            var idsArray = (");
            Write(model.KeyFields[0].Column.CsTypeName);
            WriteLiteral(@"[])ids;");
            WriteLiteral(Environment.NewLine);
            WriteLiteral(@"            using (new ConnectionHandler(conn))");
            WriteLiteral(Environment.NewLine);
            WriteLiteral(@"            {");
            WriteLiteral(Environment.NewLine);
            WriteLiteral(@"                var table = CiHelper.CreateTempTableName();");
            WriteLiteral(Environment.NewLine);
            WriteLiteral(@"                CreateIdTempTable(table, conn, trans);");
            WriteLiteral(Environment.NewLine);
            WriteLiteral(@"                CiHelper.BulkInsert(new SingleKeyDataReader<");
            Write(model.KeyFields[0].Column.CsTypeName);
            WriteLiteral(@">(idsArray), table, conn, trans);");
            WriteLiteral(Environment.NewLine);
            WriteLiteral(@"                var sql = ");
            WriteLiteral(@"@");
            WriteLiteral(@"""select ");
            WriteLiteral(Environment.NewLine);
            foreach (var line in model.GetFieldSelectLines("e."))
            {
                WriteLiteral(@"                ");
                Write(line);
                WriteLiteral(Environment.NewLine);
            }
            WriteLiteral(@"				from ");
            Write(model.Table.Id);
            WriteLiteral(@" e");
            WriteLiteral(Environment.NewLine);
            WriteLiteral(@"                inner join "" + table + ");
            WriteLiteral(@"@");
            WriteLiteral(@""" t on ");
            WriteLiteral(Environment.NewLine);
            foreach (var line in model.GetKeyEqualityLines("e.", "t.", "\";"))
            {
                WriteLiteral(@"                ");
                Write(line);
                WriteLiteral(Environment.NewLine);
            }
            WriteLiteral(@"                var result = CiHelper.ExecuteSelect(sql, new SqlParameter[0], ReadEntities, conn, trans);");
            WriteLiteral(Environment.NewLine);
            WriteLiteral(@"                CiHelper.DropTable(table, conn, trans);");
            WriteLiteral(Environment.NewLine);
            WriteLiteral(@"                return result;");
            WriteLiteral(Environment.NewLine);
            WriteLiteral(@"            }");
            WriteLiteral(Environment.NewLine);
            WriteLiteral(@"        }");
            WriteLiteral(Environment.NewLine);

            return executed = sb.ToString();
        }
    }
}
