//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace BasicFeaturesTest.StormModel
{
    using System.Data.Common;
    using System.Linq;

    public partial class StormTestContext : IStormContext
    {
        private StormCommands stormCommands;

        IQueryable<T> IStormContext.Set<T>()
        {
            return Set<T>();
        }

        IDalRepository<TDal, TQuery> IStormContext.GetDalRepository<TDal, TQuery>()
        {
            return DalRepositoryStorage.GetDalRepository<TDal, TQuery>();
        }

        public StormCommands Storm
        {
            get
            {
                return stormCommands = stormCommands ?? new StormCommands(this);
            }
        }

        public DbConnection Connection { get { return Database.Connection; } }

        public DbTransaction Transaction
        {
            get
            {
                return Database.CurrentTransaction != null ? Database.CurrentTransaction.UnderlyingTransaction : null;
            }
        }
    }
}
