//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace StormGenerator.Generation.Generators.Linq2Db
{
    using StormGenerator.Models;
    using System;
    using System.Text;
    using System.Linq;

    [System.CodeDom.Compiler.GeneratedCode("SharpRazor", "1.0.0.0")]
    internal class ContextTableLine
    {
        #region constructor
        EntityModel model;

        public ContextTableLine(EntityModel model)
        {
            this.model = model;
        }
        #endregion

        #region basic members
        private readonly StringBuilder sb = new StringBuilder();
        private string executed;

        private void WriteLiteral(string text)
        {
            if (!string.IsNullOrEmpty(text))
            {
                sb.Append(text);
            }
        }

        private void Write(object value)
        {
            if (value != null)
            {
                sb.Append(value);
            }
        }

        public override string ToString()
        {
            return executed;
        }
        #endregion

        public string Execute()
        {
            WriteLiteral(@"public ITable<");
            Write(model.Model.Name);
            WriteLiteral(@"> ");
            Write(model.Name);
            WriteLiteral(@" { get { return GetTable<");
            Write(model.Model.Name);
            WriteLiteral(@">(); } }");
            WriteLiteral(Environment.NewLine);

            return executed = sb.ToString();
        }
    }
}
