//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace StormGenerator.Generation.Generators.Linq2Db
{
    using Models;
    using System.Collections.Generic;
    using Settings;
    using System;
    using System.Text;
    using StormGenerator.Models;

    [System.CodeDom.Compiler.GeneratedCode("SharpRazor", "1.0.0.0")]
    internal class StormContext : FileGenerator
    {
        #region constructor
        GenOptions options;
        List<EntityModel> model;

        public StormContext(GenOptions options, List<EntityModel> model)
        {
            this.options = options;
            this.model = model;
        }
        #endregion

        public override string FileName => options.ContextName;

        public override string Execute()
        {
            WriteLiteral("namespace ");
            Write(options.OutputNamespace);
            WriteLiteral(Environment.NewLine);
            WriteLiteral("{");
            WriteLiteral(Environment.NewLine);
            WriteLiteral("    using LinqToDB;");
            WriteLiteral(Environment.NewLine);
            WriteLiteral("    public partial class ");
            Write(options.ContextName);
            WriteLiteral(Environment.NewLine);
            WriteLiteral("	{");
            WriteLiteral(Environment.NewLine);
            WriteLiteral("    ");
            foreach (var m in model)
            {
                Write(new ContextTableLine(m).Execute());
            }
            WriteLiteral(Environment.NewLine);
            WriteLiteral("	}	");
            WriteLiteral(Environment.NewLine);
            WriteLiteral("}");
            WriteLiteral(Environment.NewLine);

            return ToString();
        }
    }
}
